version: '2.1'

services:
  localstack:
    image: localstack:sqs
    ports:
      - "4576:4576" # SQS
    environment:
      - SERVICES=sqs
      - DEBUG=0
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0
      - SQS_PORT_EXTERNAL=4576
    volumes:
      # localstack raises error on "permission deined" if using container disk
      - ./var:/tmp/localstack
